<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agenda Telefonica</title>
  <meta name="description" content="">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <head>
    <div class="head">
      <h1>AGENDA TELEFONICA</h1>
    </div>
  </head>
  <nav class="menu">
    <a class="Menu" href="index.php">Inicio</a> |
    <a class="Menu" href="verlista.php">Ver lista </a> |
    <a class="Menu" href="Login.php">Login</a>
  </nav>
  <article class="article">
    <div class="img">
      <img src="img/logo_tec.png" class="IMG">
    </div>
    <div class="subtitle">
      <h2>EJEMPLO DE AGENDA TELEFONICA</h2>
    </div>
     <div class="nameDev">
      <h3>Néstor Gabriel Sosa Hernández</h3>
     </div>
  </article>
  <footer class="foot">
    <a class="link" target="_blank" href="https://www.merida.tecnm.mx/">www.itmerida.com</a>
  </footer>
</body>
</html>